#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-mido
Version  : 1.2.10
Release  : 64
URL      : https://files.pythonhosted.org/packages/57/1f/b067eed2314c13481e354dd32560c1d9f45d516dd44d9751b85e0e9798fc/mido-1.2.10.tar.gz
Source0  : https://files.pythonhosted.org/packages/57/1f/b067eed2314c13481e354dd32560c1d9f45d516dd44d9751b85e0e9798fc/mido-1.2.10.tar.gz
Summary  : MIDI Objects for Python
Group    : Development/Tools
License  : MIT
Requires: pypi-mido-bin = %{version}-%{release}
Requires: pypi-mido-license = %{version}-%{release}
Requires: pypi-mido-python = %{version}-%{release}
Requires: pypi-mido-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(py)
BuildRequires : pypi-pluggy
BuildRequires : pypi-pytest
BuildRequires : pypi-tox
BuildRequires : pypi-virtualenv

%description
==============================

%package bin
Summary: bin components for the pypi-mido package.
Group: Binaries
Requires: pypi-mido-license = %{version}-%{release}

%description bin
bin components for the pypi-mido package.


%package license
Summary: license components for the pypi-mido package.
Group: Default

%description license
license components for the pypi-mido package.


%package python
Summary: python components for the pypi-mido package.
Group: Default
Requires: pypi-mido-python3 = %{version}-%{release}

%description python
python components for the pypi-mido package.


%package python3
Summary: python3 components for the pypi-mido package.
Group: Default
Requires: python3-core
Provides: pypi(mido)

%description python3
python3 components for the pypi-mido package.


%prep
%setup -q -n mido-1.2.10
cd %{_builddir}/mido-1.2.10
pushd ..
cp -a mido-1.2.10 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1656394173
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 setup.py build

popd
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-mido
cp %{_builddir}/mido-1.2.10/LICENSE %{buildroot}/usr/share/package-licenses/pypi-mido/d891cc509267ee382f3cf7389f1c6f6304954ec7
cp %{_builddir}/mido-1.2.10/docs/license.rst %{buildroot}/usr/share/package-licenses/pypi-mido/f243d53f50ec9a04ef1bdf42262d8e9c6481e5ee
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -tt setup.py build install --root=%{buildroot}-v3
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/mido-connect
/usr/bin/mido-play
/usr/bin/mido-ports
/usr/bin/mido-serve

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-mido/d891cc509267ee382f3cf7389f1c6f6304954ec7
/usr/share/package-licenses/pypi-mido/f243d53f50ec9a04ef1bdf42262d8e9c6481e5ee

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
