#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: pyproject
#
Name     : pypi-mido
Version  : 1.3.0
Release  : 69
URL      : https://files.pythonhosted.org/packages/a1/33/4184e8b5aada02e9ca74ee7fdce462b023f278cabe9dd9f58a4a62c230a3/mido-1.3.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/a1/33/4184e8b5aada02e9ca74ee7fdce462b023f278cabe9dd9f58a4a62c230a3/mido-1.3.0.tar.gz
Summary  : MIDI Objects for Python
Group    : Development/Tools
License  : CC0-1.0 MIT
Requires: pypi-mido-bin = %{version}-%{release}
Requires: pypi-mido-license = %{version}-%{release}
Requires: pypi-mido-python = %{version}-%{release}
Requires: pypi-mido-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(setuptools)
BuildRequires : pypi(setuptools_scm)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
..
.. SPDX-License-Identifier: CC-BY-4.0
Mido - MIDI Objects for Python
==============================

%package bin
Summary: bin components for the pypi-mido package.
Group: Binaries
Requires: pypi-mido-license = %{version}-%{release}

%description bin
bin components for the pypi-mido package.


%package license
Summary: license components for the pypi-mido package.
Group: Default

%description license
license components for the pypi-mido package.


%package python
Summary: python components for the pypi-mido package.
Group: Default
Requires: pypi-mido-python3 = %{version}-%{release}

%description python
python components for the pypi-mido package.


%package python3
Summary: python3 components for the pypi-mido package.
Group: Default
Requires: python3-core
Provides: pypi(mido)
Requires: pypi(packaging)

%description python3
python3 components for the pypi-mido package.


%prep
%setup -q -n mido-1.3.0
cd %{_builddir}/mido-1.3.0
pushd ..
cp -a mido-1.3.0 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1691505443
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FCFLAGS="$FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FFLAGS="$FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export CXXFLAGS="$CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -m build --wheel --skip-dependency-check --no-isolation

popd

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-mido
cp %{_builddir}/mido-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/pypi-mido/d891cc509267ee382f3cf7389f1c6f6304954ec7 || :
cp %{_builddir}/mido-%{version}/LICENSES/CC0-1.0.txt %{buildroot}/usr/share/package-licenses/pypi-mido/82da472f6d00dc5f0a651f33ebb320aa9c7b08d0 || :
cp %{_builddir}/mido-%{version}/LICENSES/MIT.txt %{buildroot}/usr/share/package-licenses/pypi-mido/adadb67a9875aeeac285309f1eab6e47d9ee08a7 || :
pip install --root=%{buildroot} --no-deps --ignore-installed dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
pip install --root=%{buildroot}-v3 --no-deps --ignore-installed dist/*.whl
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/mido-connect
/usr/bin/mido-play
/usr/bin/mido-ports
/usr/bin/mido-serve

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-mido/82da472f6d00dc5f0a651f33ebb320aa9c7b08d0
/usr/share/package-licenses/pypi-mido/adadb67a9875aeeac285309f1eab6e47d9ee08a7
/usr/share/package-licenses/pypi-mido/d891cc509267ee382f3cf7389f1c6f6304954ec7

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
